var currentcameras = [
  {
    "company": "AgfaPhoto",
    "name": "AgfaPhoto 35mm black",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash that is reusable",
    "website": "",
    "launched": 2020,
    "image": "agfaphoto-35mm-black.png"
  },
  {
    "company": "AgfaPhoto",
    "name": "AgfaPhoto 35mm brown",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash that is reusable",
    "website": "",
    "launched": 2020,
    "image": "agfaphoto-35mm-brown.png"
  },
  {
    "company": "AgfaPhoto",
    "name": "AgfaPhoto 35mm red",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash that is reusable",
    "website": "",
    "launched": 2020,
    "image": "agfaphoto-35mm-red.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm QuickSnap Flash 400",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash for indoor and outdoor use",
    "website": "https://www.ishootfujifilm.com/products/detail/quicksnap-flash-400",
    "launched": 1986,
    "image": "fujifilm-quicksnap-flash-400.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm QuickSnap Waterproof",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash for underwater use",
    "website": "https://www.fujifilm.com/us/en/consumer/film-quicksnap/quicksnap/quicksnap-waterproof",
    "launched": 2021,
    "image": "fujifilm-quicksnap-waterproof.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Daylight",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera without flash for outdoor use",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 2018,
    "image": "kodak-daylight.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Fun Saver",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash for indoor and outdoor use",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 1990,
    "image": "kodak-fun-saver.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Power Flash",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash for outdoor use and low light situations",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 1989,
    "image": "kodak-power-flash.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Professional Tri-X 400",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash for indoor and outdoor use",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 2018,
    "image": "kodak-professional-tri-x-400.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Sport",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash for underwater use",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 1989,
    "image": "kodak-sport.png"
  },
  {
    "company": "Leica",
    "name": "Leica M-A (Typ 127)",
    "format": "35mm",
    "type": "rangefinder",
    "price": 3,
    "popularity": 0,
    "description": "a purely mechanical rangefinder camera",
    "website": "https://leica-camera.com/de-DE/fotografie/kameras/m/m-a-typ-127-silbern",
    "launched": 2014,
    "image": "leica-mp.png"
  },
  {
    "company": "Leica",
    "name": "Leica MP",
    "format": "35mm",
    "type": "rangefinder",
    "price": 3,
    "popularity": 0,
    "description": "a mechanical rangefinder camera with built-in light meter",
    "website": "https://leica-camera.com/de-DE/fotografie/kameras/m/mp-silbern",
    "launched": 2003,
    "image": "leica-mp.png"
  },
  {
    "company": "Linhof",
    "name": "Linhof Master Technika 3000",
    "format": "4x5",
    "type": "bellows",
    "price": 3,
    "popularity": 0,
    "description": "a high-quality flexible camera system",
    "website": "https://linhof.com/master-technika-3000-2/",
    "launched": 2006,
    "image": "linhof-master-technika-3000.png"
  },
  {
    "company": "Linhof",
    "name": "Linhof Master Technika classic",
    "format": "4x5",
    "type": "bellows",
    "price": 3,
    "popularity": 0,
    "description": "a high-quality flexible camera system",
    "website": "https://linhof.com/master-technika-classic-2/",
    "launched": 2006,
    "image": "linhof-master-technika-classic.png"
  },
  {
    "company": "Linhof",
    "name": "Linhof Techno",
    "format": "120",
    "type": "bellows",
    "price": 3,
    "popularity": 0,
    "description": "a high-quality flexible camera system",
    "website": "https://linhof.com/linhof-techno/",
    "launched": 2008,
    "image": "linhof-techno.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 135 Panoramic",
    "format": "135",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a pinhole camera made out of wood for panorama photos",
    "website": "https://ondupinhole.com/products/135-panoramic-pinhole-camera",
    "launched": 2015,
    "image": "ondu-135-panoramic.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 135 Pocket",
    "format": "135",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/135-pocket-pinhole-camera",
    "launched": 2015,
    "image": "ondu-135-pocket.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 4x5\" Large Format",
    "format": "4x5",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a large format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/4x5-large-format",
    "launched": 2015,
    "image": "ondu-4x5-large-format.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 4x5\" Large Format Rise",
    "format": "4x5",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a large format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/4x5-large-rise",
    "launched": 2015,
    "image": "ondu-4x5-large-format-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x12 Multiformat",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for panorama photos",
    "website": "https://ondupinhole.com/products/6x12-multiformat",
    "launched": 2015,
    "image": "ondu-6x12-multiformat.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x12 Rise",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for panorama photos",
    "website": "https://ondupinhole.com/products/6x12-rise",
    "launched": 2015,
    "image": "ondu-6x12-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x6 Pocket",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for square photos",
    "website": "https://ondupinhole.com/products/6x6-pocket",
    "launched": 2015,
    "image": "ondu-6x6-pocket.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x6 Rise",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for square photos",
    "website": "https://ondupinhole.com/products/6x6-rise",
    "launched": 2015,
    "image": "ondu-6x6-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x9 Classic",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/6x9-classic",
    "launched": 2015,
    "image": "ondu-6x9-classic.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x9 Rise",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/6x9-rise",
    "launched": 2015,
    "image": "ondu-6x9-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 8x10\" Giant",
    "format": "8x10",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a large format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/8x10-giant-pinhole-camera",
    "launched": 2015,
    "image": "ondu-8x10-giant.png"
  }
]