var currentcameras = [
  {
    "company": "AgfaPhoto",
    "name": "AgfaPhoto 35mm",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (available in black, brown and red)",
    "website": "https://www.lupus-imaging-media.com/agfaphoto-analogkameras/",
    "launched": 2020,
    "image": "agfaphoto-35mm.png"
  },
  {
    "company": "AgfaPhoto",
    "name": "AgfaPhoto Half Frame",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash that uses the half frame format",
    "website": "",
    "launched": 2023,
    "image": "agfaphoto-half-frame.png"
  },
  {
    "company": "dubblefilm",
    "name": "dubblefilm SHOW",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (available in black, pink and turquoise)",
    "website": "https://dubblefilm.com/collections/show-camera",
    "launched": 2020,
    "image": "dubblefilm-show.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm QuickSnap Flash 400",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash for indoor and outdoor use (loaded with Superia X-TRA 400)",
    "website": "https://www.ishootfujifilm.com/products/detail/quicksnap-flash-400",
    "manual": "manuals/fujifilm-quicksnap-flash-400.pdf",
    "launched": 1986,
    "image": "fujifilm-quicksnap-flash-400.png"
  },
  {
    "company": "Fujifilm",
    "name": "Fujifilm QuickSnap Waterproof",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash for underwater use (loaded with Superia X-TRA 800)",
    "website": "https://www.fujifilm.com/us/en/consumer/film-quicksnap/quicksnap/quicksnap-waterproof",
    "launched": 2021,
    "image": "fujifilm-quicksnap-waterproof.png"
  },
  {
    "company": "Harman",
    "name": "Harman EZ-35",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash and motorised film load, advance and rewind (loaded with Ilford HP5 Plus)",
    "website": "https://www.harmantechnology.com/harman-ez-35-reusable-camera-with-hp5",
    "manual": "manuals/harman-ez-35.pdf",
    "launched": 2021,
    "image": "harman-ez-35.png"
  },
  {
    "company": "Harman",
    "name": "Harman Reusable Camera",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (includes 2x Kentmere Pan 400)",
    "website": "https://www.harmantechnology.com/harman-reusable-camera-and-kentmere-film",
    "launched": 2019,
    "image": "harman-reusable-camera.png"
  },
  {
    "company": "Harman",
    "name": "Harman Titan 4x5 Pinhole",
    "format": "4x5",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a pinhole camera made from ABS type plastics with interchangable cones for different focal lengths",
    "website": "https://www.harmantechnology.com/harman-titan-4x5-pinhole-camera",
    "launched": 2011,
    "image": "harman-titan-4x5-pinhole.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford HP5 Plus Single Use Camera",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash (loaded with Ilford HP5 Plus)",
    "website": "https://www.harmantechnology.com/hp5-plus-single-use-camera",
    "manual": "manuals/ilford-hp5-plus-single-use-camera.pdf",
    "launched": 2012,
    "image": "ilford-hp5-plus-single-use-camera.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Ilfocolor Rapid Retro",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash for indoor and outdoor use (loaded with a 400 ISO film from Kodak)",
    "website": "https://ilford.com/product/rapid-retro-camera/",
    "launched": 2021,
    "image": "ilford-ilfocolor-rapid-retro.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Obscura",
    "format": "4x5",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a pinhole camera made from PVC that does not require a film holder",
    "website": "https://www.harmantechnology.com/obscura-by-ilford-pinhole-camera",
    "launched": 2013,
    "image": "ilford-obscura.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford Sprite 35-II",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (available in black and silver)",
    "website": "https://ilford.com/product/sprite-35-ii-camera/",
    "manual": "manuals/ilford-sprite-35-ii.pdf",
    "launched": 2021,
    "image": "ilford-sprite-35-ii.png"
  },
  {
    "company": "Ilford",
    "name": "Ilford XP2 super Single Use Camera",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash (loaded with Ilford XP2 super)",
    "website": "https://www.harmantechnology.com/xp2-super-single-use-camera",
    "manual": "manuals/ilford-xp2-super-single-use-camera.pdf",
    "launched": 2012,
    "image": "ilford-xp2-super-single-use-camera.png"
  },
  {
    "company": "Intrepid",
    "name": "Intrepid 4x5",
    "format": "4x5",
    "type": "view",
    "price": 2,
    "popularity": 0,
    "description": "A comparatively lightweight camera that can be packed compactly",
    "website": "https://intrepidcamera.co.uk/collections/camera/products/intrepid-4x5-camera",
    "manual": "",
    "launched": 2022,
    "image": "intrepid-4x5.png"
  },
  {
    "company": "Intrepid",
    "name": "Intrepid 5x7",
    "format": "5x7",
    "type": "view",
    "price": 2,
    "popularity": 0,
    "description": "A comparatively lightweight camera that can be packed compactly",
    "website": "https://intrepidcamera.co.uk/collections/camera/products/intrepid-5x7-camera",
    "manual": "",
    "launched": 2020,
    "image": "intrepid-5x7.png"
  },
  {
    "company": "Intrepid",
    "name": "Intrepid 8x10",
    "format": "8x10",
    "type": "view",
    "price": 3,
    "popularity": 0,
    "description": "A comparatively lightweight camera that can be packed compactly",
    "website": "https://intrepidcamera.co.uk/collections/camera/products/intrepid-8x10-camera",
    "manual": "",
    "launched": 2022,
    "image": "intrepid-8x10.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Daylight",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera without built-in flash for outdoor use (loaded with Kodak UltraMax 800)",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 2018,
    "image": "kodak-daylight.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Ektar H35",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free reusable plastic half frame camera with built-in flash (available in four different colors)",
    "website": "https://www.kodak.com/en/consumer/product/cameras/film/h35-film-camera",
    "launched": 2022,
    "image": "kodak-ektar-h35.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Fun Saver",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash for indoor and outdoor use (loaded with Kodak UltraMax 800)",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 1990,
    "image": "kodak-fun-saver.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak i60",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in pop-up flash (available in yellow and very peri)",
    "website": "https://www.kodak.com/en/consumer/product/cameras/film/i60",
    "launched": 2021,
    "image": "kodak-i60.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak M35",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (available in eight different colors)",
    "website": "https://www.kodak.com/en/consumer/product/cameras/film/m35",
    "manual": "manuals/kodak-m35.pdf",
    "launched": 2019,
    "image": "kodak-m35.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak M38",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with a slightly stronger built-in flash compared to the Kodak M35 (available in seven different colors)",
    "website": "https://www.kodak.com/en/consumer/product/cameras/film/m38",
    "manual": "manuals/kodak-m38.pdf",
    "launched": 2020,
    "image": "kodak-m38.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Power Flash",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash for outdoor use and low light situations (loaded with Kodak UltraMax 800)",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 1989,
    "image": "kodak-power-flash.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Professional TRI-X 400",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash for indoor and outdoor use (loaded with Kodak TRI-X 400)",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 2018,
    "image": "kodak-professional-tri-x-400.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Sport",
    "format": "135",
    "type": "disposable",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera without built-in flash for underwater use (loaded with Kodak UltraMax 800)",
    "website": "https://imaging.kodakalaris.com/photographers/film/single-use-cameras",
    "launched": 1989,
    "image": "kodak-sport.png"
  },
  {
    "company": "Kodak",
    "name": "Kodak Ultra F9",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (available in yellow and green)",
    "website": "https://www.kodak.com/en/consumer/product/cameras/film/kodak-film-camera-ultra-f9",
    "manual": "manuals/kodak-ultra-f9.pdf",
    "launched": 2021,
    "image": "kodak-ultra-f9.png"
  },
  {
    "company": "Leica",
    "name": "Leica M6",
    "format": "135",
    "type": "rangefinder",
    "price": 3,
    "popularity": 0,
    "description": "a rangefinder camera with built-in light meter",
    "website": "https://leica-camera.com/de-DE/fotografie/kameras/m/m6",
    "manual": "manuals/leica-m6.pdf",
    "launched": 1984,
    "image": "leica-m6.png"
  },
  {
    "company": "Leica",
    "name": "Leica M-A (Typ 127)",
    "format": "135",
    "type": "rangefinder",
    "price": 3,
    "popularity": 0,
    "description": "a purely mechanical rangefinder camera (available in black, silver and titan)",
    "website": "https://leica-camera.com/de-DE/fotografie/kameras/m/m-a-typ-127-silbern",
    "manual": "manuals/leica-m-a.pdf",
    "launched": 2014,
    "image": "leica-m-a.png"
  },
  {
    "company": "Leica",
    "name": "Leica MP",
    "format": "135",
    "type": "rangefinder",
    "price": 3,
    "popularity": 0,
    "description": "a rangefinder camera with built-in light meter (available in black and silver)",
    "website": "https://leica-camera.com/de-DE/fotografie/kameras/m/mp-silbern",
    "manual": "manuals/leica-mp.pdf",
    "launched": 2003,
    "image": "leica-mp.png"
  },
  {
    "company": "Linhof",
    "name": "Linhof Master Technika 3000",
    "format": "4x5",
    "type": "view",
    "price": 3,
    "popularity": 0,
    "description": "a high-quality flexible camera system",
    "website": "https://linhof.com/master-technika-3000-2/",
    "launched": 2006,
    "image": "linhof-master-technika-3000.png"
  },
  {
    "company": "Linhof",
    "name": "Linhof Master Technika classic",
    "format": "4x5",
    "type": "view",
    "price": 3,
    "popularity": 0,
    "description": "a high-quality flexible camera system",
    "website": "https://linhof.com/master-technika-classic-2/",
    "launched": 2006,
    "image": "linhof-master-technika-classic.png"
  },
  {
    "company": "Linhof",
    "name": "Linhof Techno",
    "format": "120",
    "type": "view",
    "price": 3,
    "popularity": 0,
    "description": "a high-quality flexible camera system",
    "website": "https://linhof.com/linhof-techno/",
    "launched": 2008,
    "image": "linhof-techno.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography ActionSampler clear",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera that takes four exposures with each shutter release",
    "website": "https://shop.lomography.com/actionsampler-clear",
    "launched": 1998,
    "image": "lomography-actionsampler-clear.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Diana Baby",
    "format": "110",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with interchangeable lenses",
    "website": "https://microsites.lomography.com/110-cameras/",
    "launched": 2012,
    "image": "lomography-diana-baby.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Diana F+",
    "format": "120",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple plastic camera with three focus zones that can be switched between different formats",
    "website": "https://microsites.lomography.com/diana/",
    "launched": 2007,
    "image": "lomography-diana-f-plus.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Diana Mini",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple plastic camera with four focus zones that can be switched between different formats",
    "website": "https://microsites.lomography.com/diana-mini/",
    "launched": 2012,
    "image": "lomography-diana-mini.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Diana Multi Pinhole Operator",
    "format": "120",
    "type": "pinhole",
    "price": 1,
    "popularity": 0,
    "description": "a plastic camera with three pinholes and color gels that can be switched between different formats",
    "website": "https://microsites.lomography.com/diana/",
    "launched": 2009,
    "image": "lomography-diana-multi-pinhole-operator.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Fisheye Baby",
    "format": "110",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with a fisheye lens",
    "website": "https://microsites.lomography.com/110-cameras/",
    "launched": 2012,
    "image": "lomography-fisheye-baby.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Fisheye No. 2",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free plastic camera with a fisheye lens and built-in flash",
    "website": "https://microsites.lomography.com/fisheye/",
    "launched": 2011,
    "image": "lomography-fisheye-no-2.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Horizon Kompakt",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a focus free mechanical panorama camera with a fixed aperture",
    "website": "https://microsites.lomography.com/horizon/horizon-kompakt/",
    "launched": 2005,
    "image": "lomography-horizon-kompakt.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Horizon Perfekt",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a focus free mechanical panorama camera with variable aperture and shutter speed",
    "website": "https://microsites.lomography.com/horizon/horizon-perfekt/",
    "launched": 2005,
    "image": "lomography-horizon-perfekt.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography HydroChrome Sutton’s Panoramic Belair",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a plastic camera where the lens can be filled with (colored) liquid",
    "website": "https://shop.lomography.com/hydrochrome-sutton-s-panoramic-belair-camera",
    "launched": 2020,
    "image": "lomography-hydrochrome-suttons-panoramic-belair.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Konstruktor",
    "format": "135",
    "type": "single-lens reflex",
    "price": 1,
    "popularity": 0,
    "description": "a plastic single-lens reflex camera that you have to assemble yourself",
    "website": "https://microsites.lomography.com/konstruktor/",
    "launched": 2013,
    "image": "lomography-konstruktor.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography La Sardina",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a plastic camera with two focus zones and a flash (available in a wide range of editions)",
    "website": "https://microsites.lomography.com/la-sardina/",
    "launched": 2011,
    "image": "lomography-la-sardina.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomo LC-A+",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a plastic camera with four focus zones, built-in light meter and automatic exposure",
    "website": "https://microsites.lomography.com/lca+/",
    "launched": 2006,
    "image": "lomography-lomo-lc-a-plus.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomo LC-A 120",
    "format": "120",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a plastic camera with four focus zones, built-in light meter and automatic exposure",
    "website": "https://microsites.lomography.com/lca-120/",
    "launched": 2014,
    "image": "lomography-lomo-lc-a-120.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomo LC-Wide",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a plastic camera that can be switched between full, half and square frame",
    "website": "https://microsites.lomography.com/lc-wide/",
    "launched": 2011,
    "image": "lomography-lomo-lc-wide.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography LomoMod No.1",
    "format": "120",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a cardboard camera that you have to assemble yourself and where the lens can be filled with (colored) liquid",
    "website": "https://www.lomography.com/lomomod",
    "launched": 2019,
    "image": "lomography-lomomod-no-1.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Lomo Lubitel 166+",
    "format": "120",
    "type": "twin-lens reflex",
    "price": 2,
    "popularity": 0,
    "description": "a mechanical plastic camera with a glass lens that can be switched between different formats",
    "website": "https://microsites.lomography.com/lubitel166+/",
    "launched": 2008,
    "image": "lomography-lomo-lubitel-166-plus.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Simple Use Reloadable Black and White",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with flash",
    "website": "https://microsites.lomography.com/simple-use-film-camera/",
    "launched": 2017,
    "image": "lomography-simple-use-reloadable-black-and-white.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Simple Use Reloadable Color Negative",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash color filters",
    "website": "https://microsites.lomography.com/simple-use-film-camera/",
    "launched": 2017,
    "image": "lomography-simple-use-reloadable-color-negative.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Simple Use Reloadable LomoChrome Metropolis",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash color filters",
    "website": "https://microsites.lomography.com/simple-use-film-camera/",
    "launched": 2020,
    "image": "lomography-simple-use-reloadable-lomochrome-metropolis.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Simple Use Reloadable LomoChrome Purple",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free plastic camera with built-in flash color filters",
    "website": "https://microsites.lomography.com/simple-use-film-camera/",
    "launched": 2017,
    "image": "lomography-simple-use-reloadable-lomochrome-purple.png"
  },
  {
    "company": "Lomography",
    "name": "Lomography Sprocket Rocket",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free plastic panorama camera that also exposes the film sprocket holes",
    "website": "https://microsites.lomography.com/sprocketrocket/",
    "launched": 2010,
    "image": "lomography-sprocket-rocket.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 135 Panoramic",
    "format": "135",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a pinhole camera made out of wood for panorama photos",
    "website": "https://ondupinhole.com/products/135-panoramic-pinhole-camera",
    "launched": 2015,
    "image": "ondu-135-panoramic.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 135 Pocket",
    "format": "135",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/135-pocket-pinhole-camera",
    "launched": 2015,
    "image": "ondu-135-pocket.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 4x5\" Large Format",
    "format": "4x5",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a large format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/4x5-large-format",
    "launched": 2015,
    "image": "ondu-4x5-large-format.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 4x5\" Large Format Rise",
    "format": "4x5",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a large format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/4x5-large-rise",
    "launched": 2015,
    "image": "ondu-4x5-large-format-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x12 Multiformat",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for panorama photos",
    "website": "https://ondupinhole.com/products/6x12-multiformat",
    "launched": 2015,
    "image": "ondu-6x12-multiformat.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x12 Rise",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for panorama photos",
    "website": "https://ondupinhole.com/products/6x12-rise",
    "launched": 2015,
    "image": "ondu-6x12-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x6 Pocket",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for square photos",
    "website": "https://ondupinhole.com/products/6x6-pocket",
    "launched": 2015,
    "image": "ondu-6x6-pocket.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x6 Rise",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood for square photos",
    "website": "https://ondupinhole.com/products/6x6-rise",
    "launched": 2015,
    "image": "ondu-6x6-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x9 Classic",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/6x9-classic",
    "launched": 2015,
    "image": "ondu-6x9-classic.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 6x9 Rise",
    "format": "120",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a medium format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/6x9-rise",
    "launched": 2015,
    "image": "ondu-6x9-rise.png"
  },
  {
    "company": "ONDU",
    "name": "ONDU 8x10\" Giant",
    "format": "8x10",
    "type": "pinhole",
    "price": 2,
    "popularity": 0,
    "description": "a large format pinhole camera made out of wood",
    "website": "https://ondupinhole.com/products/8x10-giant-pinhole-camera",
    "launched": 2015,
    "image": "ondu-8x10-giant.png"
  },
  {
    "company": "RETO",
    "name": "RETO Ultra Wide & Slim",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with a wide-angle lens (available in blue, cream, charcoal, olive, pink, teal and yellow)",
    "website": "https://retoproject.com/products/reto-ultra-wide-slim-film-camera",
    "launched": 2022,
    "image": "reto-ultra-wide-and-slim.png"
  },
  {
    "company": "RETO",
    "name": "RETO3D Classic",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a focus free reusable plastic camera with three lenses for creating animated Gifs with a 3D effect",
    "website": "https://retoproject.com/products/reto3d-classic",
    "launched": 2019,
    "image": "reto3d-classic.png"
  },
  {
    "company": "Somikon",
    "name": "Somikon Twin-Lens Reflex",
    "format": "135",
    "type": "twin-lens reflex",
    "price": 1,
    "popularity": 0,
    "description": "a focusable plastic twin-lens reflex camera with two apertures that you have to assemble yourself",
    "website": "http://www.somikon.de/DIY-Kamera-kit-NC-9949-919.shtml",
    "manual": "manuals/somikon-twin-lens-reflex.pdf",
    "launched": 2013,
    "image": "somikon-twin-lens-reflex.png"
  },
  {
    "company": "Superheadz",
    "name": "Superheadz Powershovel Blackbird, Fly",
    "format": "135",
    "type": "twin-lens reflex",
    "price": 2,
    "popularity": 0,
    "description": "a focusable plastic twin-lens reflex camera with two apertures (available in black, blue, red, orange, yellow and white)",
    "website": "",
    "launched": 2008,
    "image": "superheadz-powershovel-blackbird-fly.png"
  },
  {
    "company": "VibePhoto",
    "name": "Vibe 501F",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash (available in black, golden, green, pink, red and silver)",
    "website": "",
    "launched": 2021,
    "image": "vibe-501f.png"
  },
  {
    "company": "Yashica",
    "name": "Yashica MF-1",
    "format": "135",
    "type": "point & shoot",
    "price": 1,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash",
    "website": "https://www.yashica.com/mf-1",
    "launched": 2019,
    "image": "yashica-mf-1.png"
  },
  {
    "company": "Yashica",
    "name": "Yashica MF-2 super DX",
    "format": "135",
    "type": "point & shoot",
    "price": 2,
    "popularity": 0,
    "description": "a simple focus free reusable plastic camera with built-in flash and light sensor",
    "website": "https://www.yashica.com/copy-of-mf-1-snapshot-art-camera",
    "launched": 2020,
    "image": "yashica-mf-2-super-dx.png"
  }
]
