var currentcameras = [
  {
    "maker": "Clint O’Connor",
    "name": "Easy 35",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "popularity": 579,
    "description": "a 35mm pinhole camera with a 25mm focal length, producing a 24x48mm image",
    "website": "https://www.instructables.com/Easy-35-3D-Printed-Pinhole-Camera/",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:953359",
    "image": "easy-35.png"
  },
  {
    "maker": "Shengqiang Zhang",
    "name": "Falcon P-35",
    "format": "135",
    "type": "large format lens",
    "price": 0,
    "popularity": 475,
    "description": "a 35mm film camera, producing a 24x65mm image",
    "website": "",
    "launched": 2025,
    "printfiles": "https://makerworld.com/en/models/1140176-3d-printed-135-wide-format-film-camera-falcon-p-35#profileId-1142405",
    "image": "falcon-p-35.png"
  },
  {
    "maker": "Simi Fernezelyi",
    "name": "FS-1",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "popularity": 572,
    "description": "a 35mm pinhole camera",
    "website": "https://simi.hu/analogia/pinhole_camera_instructions/",
    "launched": 2020,
    "printfiles": "https://www.printables.com/model/180467-3d-printed-pinhole-camera",
    "image": "fs-1.png"
  },
  {
    "maker": "Javier Doroteo",
    "name": "Medium Format Camera Version 2",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "popularity": 1144,
    "description": "a 6x6 camera with an integrated film back and swappable frame inserts",
    "website": "",
    "launched": 2022,
    "printfiles": "https://www.printables.com/model/252405-medium-format-camera-version-2",
    "image": "medium-format-camera-version-2.png"
  },
  {
    "maker": "Javier Doroteo",
    "name": "Medium Format Camera Version 3",
    "format": "120",
    "type": "mamiya press lens",
    "price": 1,
    "popularity": 0,
    "description": "a 6x6 and 6x4.5 camera with an integrated film back",
    "website": "",
    "launched": 2025,
    "printfiles": "https://www.printables.com/model/1266099-medium-format-camera-version-3",
    "image": "medium-format-camera-version-3.png"
  },
  {
    "maker": "Ryan Oh",
    "name": "O.Zone69 Mk.7",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "popularity": 104,
    "description": "a compact 6x9 medium format film camera for Mamiya Press lenses, Horseman 6x9 backs and Mamiya RB backs",
    "website": "https://ryan5h.art/o-zone69",
    "launched": 2023,
    "printfiles": "https://makerworld.com/en/models/1377805-o-zone-mk-7-6x9-3d-print-medium-format-film-camera",
    "image": "ozone69-mk7.png"
  },
  {
    "maker": "Leo Marius",
    "name": "Open Reflex",
    "format": "135",
    "type": "nikon f lens",
    "price": 0,
    "popularity": 1757,
    "description": "a 35mm SLR camera with built-in shutter",
    "website": "https://www.instructables.com/3D-Printed-Camera-OpenReflex/",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:113865",
    "image": "open-reflex.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "P5 MUTO",
    "format": "4x5",
    "type": "pinhole",
    "price": 0,
    "popularity": 176,
    "description": "a 4x5\" pinhole camera with a 25mm focal length and a built-in shutter",
    "website": "",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1496390",
    "image": "p5-muto.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "P6*6",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 2880,
    "description": "a 6x6 pinhole camera with a 50mm focal length and a built-in shutter",
    "website": "",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:157844",
    "image": "p6x6.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "PINH5AD / P5",
    "format": "4x5",
    "type": "pinhole",
    "price": 0,
    "popularity": 0,
    "description": "a 4x5\" pinhole camera with either a 90mm or 150mm focal length and a built-in shutter",
    "website": "",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:143882",
    "image": "pinh5ad.png"
  },
  {
    "maker": "Amos Dudley",
    "name": "SLO",
    "format": "135",
    "type": "printed lens",
    "price": 0,
    "popularity": 313,
    "description": "a 35mm camera that can be fully printed with a resin printer (including the lens)",
    "website": "https://amosdudley.com/weblog/SLO-Camera",
    "launched": 2016,
    "printfiles": "https://pinshape.com/items/25871-3d-printed-slo-printed-lens-camera",
    "image": "slo.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 2020 WeirdAngle",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 0,
    "description": "a 6x6 pinhole camera with a 20mm focal length",
    "website": "",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2795991",
    "image": "terrapin-2020-weirdangle.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 2-Headed-Turtle",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 0,
    "description": "a 6x12 pinhole camera with a 50mm focal length, producing a stereo image, based on the terraPin 6x6",
    "website": "",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:1090252",
    "image": "terrapin-2-headed-turtle.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 6x6",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 0,
    "description": "a 6x6 pinhole camera with various focal length options and a built-in shutter",
    "website": "",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:495230",
    "image": "terrapin-6x6.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 6x9",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 0,
    "description": "a 6x9 pinhole camera with a 40mm focal length and a built-in shutter",
    "website": "",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:577223",
    "image": "terrapin-6x9.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin ACE",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 248,
    "description": "a 6x4.5 pinhole camera with a 25mm focal length and a built-in shutter",
    "website": "",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2653707",
    "image": "terrapin-ace.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin ACME",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 577,
    "description": "a 6x6 pinhole camera with a 25mm focal length and a built-in shutter",
    "website": "",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1724928",
    "image": "terrapin-acme.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Bijou",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 364,
    "description": "a 6x4.5 pinhole camera with a 35mm focal length and a built-in shutter, shooting vertical format in a 4:3 ratio",
    "website": "",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:728157",
    "image": "terrapin-bijou.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Bijou Sidewinder",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 65,
    "description": "a 6x4.5 pinhole camera with a 35mm focal length and a built-in shutter, based on the terraPin Bijou",
    "website": "",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:1167655",
    "image": "terrapin-bijou-sidewinder.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Box Turtle",
    "format": "4x5",
    "type": "pinhole",
    "price": 0,
    "popularity": 95,
    "description": "a 4x5\" pinhole camera with either a 35mm or 75mm focal length and a built-in shutter",
    "website": "",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2206746",
    "image": "terrapin-box-turtle.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Kaiju",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 567,
    "description": "a 6x18 pinhole camera with a 86mm focal length and a built-in shutter",
    "website": "",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:876457",
    "image": "terrapin-kaiju.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Obot",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 89,
    "description": "a 6x6 pinhole camera with a 29mm focal length and a built-in remote controlled shutter",
    "website": "",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2505619",
    "image": "terrapin-obot.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin OSKAR",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 399,
    "description": "a 6x6 pinhole camera with a 29mm focal length and a built-in shutter",
    "website": "",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1835844",
    "image": "terrapin-oskar.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin OSKAR Tuxedo",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 212,
    "description": "a 6x9 pinhole camera with a 29mm focal length and a built-in shutter",
    "website": "",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2375808",
    "image": "terrapin-oskar-tuxedo.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin OSKAR^2",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 76,
    "description": "a 6x12 pinhole camera with a 29mm focal length and a built-in shutter, producing a stereo image",
    "website": "",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2622458",
    "image": "terrapin-oskar2.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Prime",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "popularity": 320,
    "description": "a 6x6 pinhole camera with a 27mm focal length and a built-in shutter",
    "website": "",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1253008",
    "image": "terrapin-prime.png"
  },
  {
    "maker": "Raul Paz",
    "name": "Vega 4x5",
    "format": "4x5",
    "type": "large format lens",
    "price": 0,
    "popularity": 206,
    "description": "a remix of The Standard 4x5 from Standard Cameras, adding features, simplifying assembly and using more widely avaliable materials",
    "website": "",
    "launched": 2023,
    "printfiles": "https://makerworld.com/en/models/114356-vega-4x5-view-camera",
    "image": "vega-4x5-view-camera.png"
  },
]
