var currentcameras = [
  {
    "maker": "Quentin Orhant",
    "name": "3D Printed Pinhole",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera with a built-in shutter",
    "website": "https://quentino.io/3d-printed-pinhole",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:531244",
    "image": "3d-printed-pinhole.png"
  },
  {
    "maker": "Jørgen Kløvstad",
    "name": "4x5 Camera",
    "format": "4x5",
    "type": "large format lens",
    "price": 0,
    "description": "a 4x5\" camera for Nikkor 75mm large format lenses",
    "launched": 2019,
    "printfiles": "https://www.printables.com/model/16309-4x5-camera-for-75mm-lens-and-fotoman-helical-focus",
    "image": "4x5-camera.png"
  },
  {
    "maker": "Torsten Spiller",
    "name": "Agfa Ansco Plenax PD 16 Conversion",
    "format": "120",
    "type": "large format lens",
    "price": 0,
    "description": "a 6x12 camera for large format lenses",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:3252136",
    "image": "agfa-ansco-plenax-pd-16-conversion.png"
  },
  {
    "maker": "KV",
    "name": "All 3D Printed Camera",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera with a built-in shutter",
    "launched": 2022,
    "printfiles": "https://www.printables.com/model/250535-all-3d-printed-camera",
    "image": "all-3d.png"
  },
  {
    "maker": "Yoni De Beule",
    "name": "Anastigmat Camera",
    "format": "135",
    "type": "large format lens",
    "price": 0,
    "description": "a 35mm camera for the Anastigmat 50mm f/4.5 enlarger lens",
    "launched": 2019,
    "printfiles": "https://www.thingiverse.com/thing:3487333",
    "image": "anastigmat.png"
  },
  {
    "maker": "Damien Humby",
    "name": "Argent Eye",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x7 camera for Mamiya Press lenses and Mamiya Press 67 backs",
    "launched": 2020,
    "printfiles": "https://github.com/DamienHazard/Argent-eye",
    "image": "argent-eye.png"
  },
  {
    "maker": "Mario Machon",
    "name": "Big Wide",
    "format": "wide",
    "type": "large format lens",
    "price": 0,
    "description": "an Instax wide camera for large format lenses and Lomograflok film backs",
    "website": "https://sprkplg.com/big-wide-diy/",
    "launched": 2023,
    "printfiles": "https://www.printables.com/model/435598-big-wide-camera-big-shot-style-instax-wide",
    "image": "big-wide.png"
  },
  {
    "maker": "Ethan Moses",
    "name": "Cameradactyl Brancopan",
    "format": "135",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 35mm camera for Mamiya Press lenses, producing a 58x24mm panoramic image",
    "website": "https://www.cameradactyl.com/brancopan",
    "video": "https://www.youtube.com/watch?v=rb5aX-7nSrM",
    "launched": 2019,
    "printfiles": "https://github.com/cameradactyl/Brancopan",
    "image": "cameradactyl-brancopan.png"
  },
  {
    "maker": "Ethan Moses",
    "name": "Cameradactyl Pinholio",
    "format": "custom",
    "type": "pinhole",
    "price": 1,
    "description": "a pinhole camera with a 50mm focal length, where the 63x63mm photographic paper can be developed inside the camera",
    "video": "https://www.youtube.com/watch?v=b2tMdB5MLHM",
    "launched": 2019,
    "printfiles": "https://www.cameradactyl.com/buttergrip/p/pinholiofiles",
    "image": "cameradactyl-pinholio.png"
  },
  {
    "maker": "Clint O’Connor",
    "name": "Easy 35",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera with a 25mm focal length, producing a 24x48mm image",
    "website": "https://www.instructables.com/Easy-35-3D-Printed-Pinhole-Camera/",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:953359",
    "image": "easy-35.png"
  },
  {
    "maker": "Evan Butson",
    "name": "EB 617 MK II",
    "format": "4x5",
    "type": "large format lens",
    "price": 2,
    "description": "a view camera for 6x17 or 4x5\" and large format lenses",
    "video": "https://www.youtube.com/watch?v=-yIITSnjUXc",
    "launched": 2024,
    "printfiles": "https://www.thefilmlaundry.com/shop/p/eb-617-mk-ii-digital-plans",
    "image": "eb-617-mk-ii.png"
  },
  {
    "maker": "Shengqiang Zhang",
    "name": "Falcon P-35",
    "format": "135",
    "type": "large format lens",
    "price": 0,
    "description": "a 35mm camera, producing a 65x24mm panoramic image",
    "video": "https://www.bilibili.com/video/BV1vsFte8EmW/?buvid=XY2A01B2AC996EB93A337D28D7E07CDB67643",
    "launched": 2025,
    "printfiles": "https://makerworld.com/en/models/1140176-3d-printed-135-wide-format-film-camera-falcon-p-35",
    "image": "falcon-p-35.png"
  },
  {
    "maker": "Jackson Bohm",
    "name": "Film Camera",
    "format": "135",
    "type": "nikon f lens",
    "price": 0,
    "description": "a 35mm camera for Nikon F lenses with a built-in shutter",
    "launched": 2022,
    "printfiles": "https://www.printables.com/model/229384-35mm-film-camera",
    "image": "film-camera.png"
  },
  {
    "maker": "David Hennen",
    "name": "Fixed Focus 6x9",
    "format": "120",
    "type": "large format lens",
    "price": 0,
    "description": "a 6x9 camera for large format lenses and Plaubel roll film backs",
    "launched": 2023,
    "printfiles": "https://www.thingiverse.com/thing:5818679",
    "image": "fixed-focus-6x9.png"
  },
  {
    "maker": "Rimantas Petrauskas",
    "name": "Frankenpan",
    "format": "135",
    "type": "medium format lens",
    "price": 0,
    "description": "a 35mm camera, converted from a Praktica MTL5B, producing 59.4x24mm panoramic images",
    "launched": 2023,
    "printfiles": "https://www.printables.com/model/559448-35mm-panoramic-film-camera",
    "image": "frankenpan.png"
  },
  {
    "maker": "Simi Fernezelyi",
    "name": "FS-1",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera",
    "website": "https://simi.hu/analogia/pinhole_camera_instructions/",
    "video": "https://www.youtube.com/watch?v=c4x_5QqiJh8",
    "launched": 2020,
    "printfiles": "https://www.printables.com/model/180467-3d-printed-pinhole-camera",
    "image": "fs-1.png"
  },
  {
    "maker": "Dora Goodman",
    "name": "Goodman Axis",
    "format": "120",
    "type": "large format lens",
    "price": 0,
    "description": "a 6x7 camera for large format lenses and Mamiya RB backs",
    "website": "https://doragoodman.com/goodlab-project/goodman-axis/",
    "launched": 2019,
    "printfiles": "https://drive.google.com/drive/folders/1tzFK5fTDOcdvB5aYtcamEl48ZURXRKI_",
    "image": "goodman-axis.png"
  },
  {
    "maker": "Dora Goodman",
    "name": "Goodman One",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x7 camera for Mamiya Press lenses and Mamiya RB backs",
    "website": "https://doragoodman.com/goodlab-project/goodman-one/",
    "launched": 2018,
    "printfiles": "https://drive.google.com/drive/folders/1W-LCbcWPWMWEfB4B-t7vBA9UP-vQHv_8",
    "image": "goodman-one.png"
  },
  {
    "maker": "Dora Goodman",
    "name": "Goodman Zone",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x7 camera for Mamiya Press lenses and Mamiya RB backs",
    "website": "https://doragoodman.com/goodlab-project/goodman-zone-medium-format-film-camera/",
    "video": "https://www.youtube.com/watch?v=7F8DniqB9i8&list=PLXaU0-pltbRCaJciKL_FLO-YxoMzZEMvg",
    "launched": 2019,
    "printfiles": "https://drive.google.com/drive/folders/1uPFNM-4rCeAAwdD-yL9Mr0cwltU40PPg",
    "image": "goodman-zone.png"
  },
  {
    "maker": "Denis Aminev",
    "name": "infidex 176",
    "format": "135",
    "type": "medium format lens",
    "price": 0,
    "description": "a 35mm camera for Mamiya TLR lenses, producing 72x24mm panoramic images",
    "website": "https://timetowaste.ru/en_infidex",
    "video": "https://www.youtube.com/watch?v=zv_Ho8Yjjiw",
    "launched": 2024,
    "printfiles": "https://drive.google.com/file/d/1Av8KrTQc2T-bhxpaDzldreE2Yz74lLlQ",
    "image": "infidex-176.png"
  },
  {
    "maker": "Josh Gladstone",
    "name": "Jankstax One",
    "format": "mini",
    "type": "glass lens",
    "price": 0,
    "description": "an Instax mini camera with a 100mm focal length and a built-in shutter",
    "video": "https://www.youtube.com/watch?v=n-TAC5FUcVg",
    "launched": 2025,
    "printfiles": "https://www.thingiverse.com/thing:6981670",
    "image": "jankstax-one.png"
  },
  {
    "maker": "Kaworu Chang",
    "name": "K16x",
    "format": "135",
    "type": "pinhole",
    "price": 1,
    "description": "a 35mm pinhole camera with a 16mm focal length and a built-in shutter, producing a 58x24mm panoramic image",
    "video": "https://www.youtube.com/watch?v=2R5Oznh-rhg",
    "launched": 2024,
    "printfiles": "https://cults3d.com/en/3d-model/gadget/k16x-a-3d-printable-135-film-16mm-ultra-wide-pinhole-camera",
    "image": "k16x.png"
  },
  {
    "maker": "Mario Machon",
    "name": "Ligero69",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x9 camera for Mamiya Press lenses and Mamiya Press roll film backs",
    "website": "https://sprkplg.com/product-tag/l69/",
    "launched": 2020,
    "printfiles": "https://www.printables.com/model/48122-ligero69-camera-body-for-mamiya-press-lens-m-mount",
    "image": "ligero69.png"
  },
  {
    "maker": "Mario Machon",
    "name": "LigeroLG / GansoLG",
    "format": "wide",
    "type": "mamiya press lens",
    "price": 0,
    "description": "an Instax wide camera for Mamiya Press lenses or Polaroid 600SE lenses and Lomograflok film backs",
    "website": "https://sprkplg.com/product-tag/llg/",
    "launched": 2022,
    "printfiles": "https://www.printables.com/model/183913-ligerolg-gansolg-camera-body-for-lomograflok-mamiy",
    "image": "ligerolg.png"
  },
  {
    "maker": "Albert Cornelissen",
    "name": "LRF45",
    "format": "4x5",
    "type": "large format lens",
    "price": 0,
    "description": "a 4x5\" camera for large format lenses and a LiDAR-powered rangefinder",
    "website": "https://github.com/acornelissen/IDENTIDEM.design-LRF45",
    "launched": 2024,
    "printfiles": "https://www.printables.com/model/718784-lrf45-a-large-format-4x5-rangefinder",
    "image": "lrf45.png"
  },
  {
    "maker": "Kevin Kadooka",
    "name": "Lux",
    "format": "120",
    "type": "glass lens",
    "price": 0,
    "description": "a 6x6 camera with a 65mm focal length and a built-in electronically controlled shutter",
    "website": "https://www.flickr.com/photos/frostedbutts/albums/72157638372089455/",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:1657138",
    "image": "lux.png"
  },
  {
    "maker": "Javier Doroteo",
    "name": "Medium Format Camera Version 2",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x6 camera with an integrated film back and swappable frame inserts",
    "video": "https://www.youtube.com/watch?v=_GxiANVp2mk",
    "launched": 2022,
    "printfiles": "https://www.printables.com/model/252405-medium-format-camera-version-2",
    "image": "medium-format-camera-version-2.png"
  },
  {
    "maker": "Javier Doroteo",
    "name": "Medium Format Camera Version 3",
    "format": "120",
    "type": "mamiya press lens",
    "price": 1,
    "description": "a 6x6 and 6x4.5 camera with an integrated film back",
    "video": "https://www.youtube.com/watch?v=NT_dC0Two10",
    "launched": 2025,
    "printfiles": "https://www.printables.com/model/1266099-medium-format-camera-version-3",
    "image": "medium-format-camera-version-3.png"
  },
  {
    "maker": "Albert Cornelissen",
    "name": "MRF",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a camera for 6x7, 6x6, 6x4.5 or 35mm panorama images with a LiDAR-powered rangefinder",
    "website": "https://github.com/acornelissen/IDENTIDEM.design-MRF",
    "video": "https://www.instagram.com/p/C63eiv-o6UP",
    "launched": 2024,
    "printfiles": "https://www.printables.com/model/881863-mrf-a-lidar-powered-lens-coupled-medium-format-fil",
    "image": "mrf.png"
  },
  {
    "maker": "Ryan Oh",
    "name": "O.Zone69 Mk.7",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x9 camera for Mamiya Press lenses, Horseman 6x9 backs and Mamiya RB backs",
    "website": "https://ryan5h.art/o-zone69",
    "video": "https://www.youtube.com/watch?v=REgRH5elXP0",
    "launched": 2023,
    "printfiles": "https://makerworld.com/en/models/1377805-o-zone-mk-7-6x9-3d-print-medium-format-film-camera",
    "image": "ozone69-mk7.png"
  },
  {
    "maker": "Jørgen Kløvstad",
    "name": "Open 4x5 Rail Camera",
    "format": "4x5",
    "type": "large format lens",
    "price": 0,
    "description": "a 4x5\" camera for large format lenses",
    "launched": 2023,
    "printfiles": "https://www.printables.com/model/555095-open-4x5-rail-camera-wip",
    "image": "open-4x5-rail-camera.png"
  },
  {
    "maker": "Jørgen Kløvstad",
    "name": "Open 6x12, 6x17 and 6x24 Panoramic Camera",
    "format": "120",
    "type": "large format lens",
    "price": 0,
    "description": "a collection of 6x12, 6x17 and 6x24 cameras for large format lenses",
    "launched": 2021,
    "printfiles": "https://www.printables.com/model/99364-open-6x12-6x17-and-6x24-panoramic-camera",
    "image": "open-6x17-camera.png"
  },
  {
    "maker": "Leo Marius",
    "name": "Open Reflex",
    "format": "135",
    "type": "nikon f lens",
    "price": 0,
    "description": "a 35mm SLR camera for Nikon F lenses with a built-in shutter",
    "website": "https://www.instructables.com/3D-Printed-Camera-OpenReflex/",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:113865",
    "image": "open-reflex.png"
  },
  {
    "maker": "Kevin Valverde",
    "name": "Original Camera",
    "format": "4x5",
    "type": "large format lens",
    "price": 0,
    "description": "a 4x5\" camera for large format lenses",
    "launched": 2022,
    "printfiles": "https://www.printables.com/model/250649-4x5-large-format-camera",
    "image": "original-camera.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "P5 MUTO",
    "format": "4x5",
    "type": "pinhole",
    "price": 0,
    "description": "a 4x5\" pinhole camera with a 25mm focal length and a built-in shutter",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1496390",
    "image": "p5-muto.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "P6*6",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 50mm focal length and a built-in shutter",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:157844",
    "image": "p6x6.png"
  },
  {
    "maker": "John Kossik",
    "name": "Panoramic 6x14",
    "format": "120",
    "type": "large format lens",
    "price": 0,
    "description": "a 6x14 camera for large format lenses",
    "website": "https://www.japancamerahunter.com/2016/09/camera-geekery-%ef%bf%bc3d-printed-panoramic-6x14-camera/",
    "launched": 2016,
    "printfiles": "https://www.printables.com/model/1200495-panoramic-6x14-camera",
    "image": "panoramic-6x14.png"
  },
  {
    "maker": "Javier Fernandez",
    "name": "Panoramic Camera",
    "format": "135",
    "type": "plastic lens",
    "price": 0,
    "description": "a 35mm camera with a plastic lens from a polaroid camera, producing 72x24mm panoramic images",
    "launched": 2020,
    "printfiles": "https://www.myminifactory.com/object/3d-print-panoramic-camera-with-polaroid-lens-111534",
    "image": "panoramic-camera.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "PINH5AD / P5",
    "format": "4x5",
    "type": "pinhole",
    "price": 0,
    "description": "a 4x5\" pinhole camera with either a 90mm or 150mm focal length and a built-in shutter",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:143882",
    "image": "pinh5ad.png"
  },
  {
    "maker": "Yode",
    "name": "Pinhole 135 Camera Mini",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera with a 24mm focal length",
    "launched": 2013,
    "printfiles": "https://www.thingiverse.com/thing:181764",
    "image": "pinhole-135-camera-mini.png"
  },
  {
    "maker": "Javier Fernandez",
    "name": "Pinhole Camera",
    "format": "custom",
    "type": "pinhole",
    "price": 0,
    "description": "a pinhole camera using 89x89mm photographic paper",
    "launched": 2020,
    "printfiles": "https://www.myminifactory.com/object/3d-print-pinhole-camera-115726",
    "image": "pinhole-camera.png"
  },
  {
    "maker": "Mark Hiltz",
    "name": "Pioneer",
    "format": "120",
    "type": "glass lens",
    "price": 0,
    "description": "a 6x6 camera with a 60mm focal length and a built-in shutter",
    "website": "https://www.instagram.com/pioneer_camera/",
    "launched": 2025,
    "printfiles": "https://drive.google.com/drive/folders/1HPYxniFw3XWP9GWbdEW4byyxlQdUplFb",
    "image": "pioneer.png"
  },
  {
    "maker": "Albert Cornelissen",
    "name": "POLA.SLR1",
    "format": "i-type",
    "type": "large format lens",
    "price": 0,
    "description": "an SLR camera for Polaroid i-Type with a 150mm large format lens and a processing unit from a OneStep 2",
    "launched": 2023,
    "printfiles": "https://www.printables.com/model/539989-polaslr1-polaroid-slr",
    "image": "pola-slr1.png"
  },
  {
    "maker": "Yoni De Beule",
    "name": "Rapax Camera",
    "format": "135",
    "type": "large format lens",
    "price": 0,
    "description": "a 35mm camera for the Rapax 101mm f/4.5 large format lens",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:705782",
    "image": "rapax.png"
  },
  {
    "maker": "Dora Goodman",
    "name": "SCURA 35mm",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera with a 50mm focal length and a built-in shutter, producing a 60x25mm panorama image",
    "website": "https://doragoodman.com/goodlab-project/scura-pinhole-camera/",
    "video": "https://www.youtube.com/watch?v=WHgHGF2g21E&list=PLXaU0-pltbRBPiwEMGUoDFvNEtogUp-fs",
    "launched": 2020,
    "printfiles": "https://drive.google.com/drive/folders/1fProA9swurpK6Qd5l8z9SjZhRs8J7bOq",
    "image": "scura-35mm.png"
  },
  {
    "maker": "Dora Goodman",
    "name": "SCURA 6x6",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 50mm focal length and a built-in shutter",
    "website": "https://doragoodman.com/goodlab-project/scura-pinhole-camera/",
    "launched": 2020,
    "printfiles": "https://drive.google.com/drive/folders/1S6Lqluq48TG2c3v3EJOrM12Ks8-SqXMU",
    "image": "scura-6x6.png"
  },
  {
    "maker": "Jacob Jaeggli",
    "name": "Sidewinder Snakeskin",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x4.5 pinhole camera with a 25mm focal length, based on the terraPin Bijou Sidewinder",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2813550",
    "image": "sidewinder-snakeskin.png"
  },
  {
    "maker": "Amos Dudley",
    "name": "SLO",
    "format": "135",
    "type": "printed lens",
    "price": 0,
    "description": "a 35mm camera that can be fully printed with a resin printer (including the lens)",
    "website": "https://amosdudley.com/weblog/SLO-Camera",
    "launched": 2016,
    "printfiles": "https://pinshape.com/items/25871-3d-printed-slo-printed-lens-camera",
    "image": "slo.png"
  },
  {
    "maker": "Drew Nikonowicz",
    "name": "Standard 4x5 2.0",
    "format": "4x5",
    "type": "large format lens",
    "price": 1,
    "description": "a 4x5\" camera for large format lenses",
    "video": "https://www.youtube.com/watch?v=d4ge8cptiso",
    "launched": 2023,
    "printfiles": "https://standardcameras.com/products/standard-4x5-2-0-download",
    "image": "standard.png"
  },
  {
    "maker": "Quentin Orhant",
    "name": "Sténopé paramétrique",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a parametric medium format pinhole camera with a built-in shutter",
    "website": "https://quentino.io/stenope-parametrique",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1769993",
    "image": "stenope-parametrique.png"
  },
  {
    "maker": "Damien Humby",
    "name": "Super 67",
    "format": "120",
    "type": "mamiya press lens",
    "price": 0,
    "description": "a 6x7 camera for Mamiya Press lenses and Mamiya RB backs",
    "launched": 2020,
    "printfiles": "https://github.com/DamienHazard/Super-67",
    "image": "super-67.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 2020 WeirdAngle",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 20mm focal length",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2795991",
    "image": "terrapin-2020-weirdangle.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 2-Headed-Turtle",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x12 pinhole camera with a 50mm focal length, producing a stereo image, based on the terraPin 6x6",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:1090252",
    "image": "terrapin-2-headed-turtle.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 6x6",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with various focal length options and a built-in shutter",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:495230",
    "image": "terrapin-6x6.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin 6x9",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x9 pinhole camera with a 40mm focal length and a built-in shutter",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:577223",
    "image": "terrapin-6x9.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin ACE",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x4.5 pinhole camera with a 25mm focal length and a built-in shutter",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2653707",
    "image": "terrapin-ace.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin ACME",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 25mm focal length and a built-in shutter",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1724928",
    "image": "terrapin-acme.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Bijou",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x4.5 pinhole camera with either a 25mm or 35mm focal length and a built-in shutter, shooting vertical format in a 4:3 ratio",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:728157",
    "image": "terrapin-bijou.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Bijou Sidewinder",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x4.5 pinhole camera with either a 25mm or 35mm focal length and a built-in shutter, based on the terraPin Bijou",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:1167655",
    "image": "terrapin-bijou-sidewinder.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Box Turtle",
    "format": "4x5",
    "type": "pinhole",
    "price": 0,
    "description": "a 4x5\" pinhole camera with either a 35mm or 75mm focal length and a built-in shutter",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2206746",
    "image": "terrapin-box-turtle.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Kaiju",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x18 pinhole camera with a 86mm focal length and a built-in shutter",
    "launched": 2015,
    "printfiles": "https://www.thingiverse.com/thing:876457",
    "image": "terrapin-kaiju.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Obot",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 29mm focal length and a built-in remote controlled shutter",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2505619",
    "image": "terrapin-obot.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin OSKAR",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 29mm focal length and a built-in shutter",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1835844",
    "image": "terrapin-oskar.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin OSKAR Tuxedo",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x9 pinhole camera with a 29mm focal length and a built-in shutter",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2375808",
    "image": "terrapin-oskar-tuxedo.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin OSKAR^2",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x12 pinhole camera with a 29mm focal length and a built-in shutter, producing a stereo image",
    "launched": 2018,
    "printfiles": "https://www.thingiverse.com/thing:2622458",
    "image": "terrapin-oskar2.png"
  },
  {
    "maker": "Todd Schlemmer",
    "name": "terraPin Prime",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a 27mm focal length and a built-in shutter",
    "launched": 2016,
    "printfiles": "https://www.thingiverse.com/thing:1253008",
    "image": "terrapin-prime.png"
  },
  {
    "maker": "Torben Ross",
    "name": "Tiny 120 Pinhole Camera",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x6 pinhole camera with a built-in shutter",
    "website": "https://www.torbenross.com/2017/09/29/tiny-6x6-120-pinhole/",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2557065",
    "image": "tiny-120-pinhole-camera.png"
  },
  {
    "maker": "Torben Ross",
    "name": "Tiny Pinhole Camera",
    "format": "135",
    "type": "pinhole",
    "price": 0,
    "description": "a 35mm pinhole camera with a built-in shutter",
    "website": "https://www.torbenross.com/2017/09/14/tiny-pinhole-camera/",
    "video": "https://www.youtube.com/watch?v=GX6EKaUGzWo",
    "launched": 2017,
    "printfiles": "https://www.thingiverse.com/thing:2498620",
    "image": "tiny-pinhole-camera.png"
  },
  {
    "maker": "Raul Paz",
    "name": "Vega 4x5",
    "format": "4x5",
    "type": "large format lens",
    "price": 0,
    "description": "a remix of The Standard 4x5, adding features, simplifying assembly and using more widely avaliable materials",
    "launched": 2023,
    "printfiles": "https://makerworld.com/en/models/114356-vega-4x5-view-camera",
    "image": "vega-4x5-view-camera.png"
  },
  {
    "maker": "Scott Mayson",
    "name": "Widepan X",
    "format": "120",
    "type": "pinhole",
    "price": 0,
    "description": "a 6x12 pinhole camera with a built-in shutter",
    "website": "https://www.flickr.com/photos/scottmayson/albums/72157643492239485/",
    "launched": 2014,
    "printfiles": "https://www.thingiverse.com/thing:323758",
    "image": "widepan-x.png"
  }
]
